name: GUT

on:
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci:3.5

    steps:
    - uses: actions/checkout@v2

    - name: Import Resources
      run: |
        godot --export "Linux/X11" /no-file

    - name: Run Tests
      run: |
        godot --path ./ -s addons/gut/gut_cmdln.gd -gexit -ginclude_subdirs -gdir=res://tests