name: GUT

on:
  pull_request:
    branches: [ main ]

env:
  GODOT_VERSION: 3.5
  PROJECT_PATH: project/

jobs:
  test:

    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci:3.5

    steps:
    - uses: actions/checkout@v2
    
    - name: (re)import resources
      run: |
        cd ${PROJECT_PATH}
        godot --export "Linux/X11" /no-file
   
    - name: Run Tests
      if: ${{ always() }}
      run: |
        godot -s addons/gut/gut_cmdln.gd -d --path $PWD -gdir=res://test/unit -ginclude_subdirs -gexit
